apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: helm-secret-template
  apiVersion: v1
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: helm-secret
    labels:
      app: infinispan-helm
  type: Opaque
  stringData:
    # The "monitor" user authenticates with the Prometheus ServiceMonitor.
    username: monitor
    # The password for the "monitor" user.
    password: password
    # The key must be 'identities-batch'.
    # The content is "user create" commands for the Data Grid CLI.
    identities-batch: |-
      user create authorized -p Authorized-password! -g authorized-role
      user create dev_user -p dev_password -g authorized-role
      user create unauthorized -p Unauthorized-password!
      user create monitor -p password --users-file metrics-users.properties --groups-file metrics-groups.properties
