apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: server-jar-pvc
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: Pod
  metadata:
    name: server-jar-pod
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  spec:
    securityContext:
      fsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
    volumes:
      - name: server-jar-pv
        persistentVolumeClaim:
          claimName: server-jar-pvc
    containers:
      - name: server-jar-pod
        image: registry.redhat.io/datagrid/datagrid-8-rhel8:1.3
        volumeMounts:
          - mountPath: /tmp/libs
            name: server-jar-pv
kind: List
metadata: {}
