apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  stringData:
    identities.yaml: |-
      credentials:
        - username: authorized
          password: Authorized-password!
          roles:
          - authorized-role
        - username: dev_user
          password: dev_password
          roles:
          - authorized-role
        - username: unauthorized
          password: Unauthorized-password!
  metadata:
    name: operator-secret
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  type: Opaque
- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: infinispan-cluster
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  spec:
    dependencies:
      artifacts:
        - url: http://server-jar-provider:8080/server.jar
    security:
      authorization:
        roles:
          - name: authorized-role
            permissions:
            - ALL
        enabled: true
      endpointEncryption:
        type: None
        clientCert: None
      endpointAuthentication: true
      endpointSecretName: operator-secret
    service:
      type: DataGrid
      container:
        ephemeralStorage: true
    expose:
      type: NodePort
      nodePort: 31222
    replicas: 2
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: proto-cache
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  spec:
    clusterName: infinispan-cluster
    name: proto-cache
    template: |-
      distributedCache:
        ### Identical cache config between Helm and Operator (If this cache 
        ### config is updated, make sure to apply the change in both 
        ### helm-chart.yaml and operator-resources.yaml)
        mode: "SYNC"
        owners: "2"
        statistics: "true"
        encoding:
          mediaType: "application/x-protostream"
        security:
          authorization:
            roles: "authorized-role"
        persistence:
          store:
            class: "com.redhat.rhdg.demo.server.loader.CustomStore"
            segmented: "false"
        indexing:
          indexed-entities:
          - rhdg_demo.ProtoValue
- apiVersion: infinispan.org/v2alpha1
  kind: Cache
  metadata:
    name: serial-cache
    labels:
      app: infinispan-operator
      app.kubernetes.io/component: infinispan-operator
      app.kubernetes.io/instance: infinispan-operator
  spec:
    clusterName: infinispan-cluster
    name: serial-cache
    template: |-
      distributedCache:
        ### Identical cache config between Helm and Operator (If this cache 
        ### config is updated, make sure to apply the change in both 
        ### helm-chart.yaml and operator-resources.yaml)
        mode: "SYNC"
        owners: "2"
        statistics: "true"
        encoding:
          mediaType: "application/x-java-serialized-object"
        security:
          authorization:
            roles: "authorized-role"
kind: List
metadata: {}
