apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: s2i-single
  apiVersion: v1
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: s2i-single
    name: s2i-single
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-single
    labels:
      app: s2i-single
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 's2i-single:latest'
    resources: {}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: registry.redhat.io/jboss-eap-8/eap8-openjdk17-builder-openshift-rhel8:latest
        env:
          - name: CUSTOM_INSTALL_DIRECTORIES
            value: extensions
        incremental: true
        forcePull: true
    source:
      type: Git
      git:
        uri: 'https://github.com/redhat-cop/appdev-cop.git'
        ref: main
      contextDir: jboss-eap-ocp
    triggers:
      - type: ConfigChange
    runPolicy: Serial
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
    name: s2i-single
    labels:
      app: s2i-single
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: s2i-single
    template:
      metadata:
        name: s2i-single
        labels:
          app: s2i-single
      spec:
        containers:
          - resources: {}
            readinessProbe:
              httpGet:
                path: /health/ready
                port: admin
                scheme: HTTP
              initialDelaySeconds: 10
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: s2i-single
            livenessProbe:
              httpGet:
                path: /health/live
                port: admin
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            env:
              - name: JGROUPS_PING_PROTOCOL
                value: dns.DNS_PING
              - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                value: '8888'
              - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
                value: 'false'
              - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                value: s2i-single-ping
              - name: ENV_FILES
                value: /etc/extensions/*
            ports:
              - name: jolokia
                containerPort: 8778
                protocol: TCP
              - name: http
                containerPort: 8080
                protocol: TCP
              - name: ping
                containerPort: 8888
                protocol: TCP
              - name: admin
                containerPort: 9990
                protocol: TCP
            imagePullPolicy: Always
            startupProbe:
              httpGet:
                path: /health/live
                port: admin
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePolicy: File
            image: s2i-single:latest
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        schedulerName: default-scheduler
    strategy:
      type: Recreate
    progressDeadlineSeconds: 600
- kind: Service
  apiVersion: v1
  metadata:
    name: s2i-single-ping
    labels:
      app: s2i-single
  spec:
    clusterIP: None
    publishNotReadyAddresses: true
    ipFamilies:
      - IPv4
    ports:
      - name: ping
        protocol: TCP
        port: 8888
        targetPort: 8888
    internalTrafficPolicy: Cluster
    clusterIPs:
      - None
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    sessionAffinity: None
    selector:
      app: s2i-single
- kind: Service
  apiVersion: v1
  metadata:
    name: s2i-single
    labels:
      app: s2i-single
  spec:
    clusterIP: None
    publishNotReadyAddresses: true
    ipFamilies:
      - IPv4
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    internalTrafficPolicy: Cluster
    clusterIPs:
      - None
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    sessionAffinity: None
    selector:
      app: s2i-single
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: s2i-single
    name: s2i-single
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: s2i-single
      weight: 100
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

